services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: corazza-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=
      - DIRECT_URL=
    volumes:
      - .:/app
      - /app/node_modules

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: corazza-web
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000/api"
    depends_on:
      - api
    volumes:
      - .:/app
      - /app/node_modules
